### ISSUE TITLE
correcion del trabajo

### ISSUE THREAD

**Issue by marianoCosco** [FacundoVillafane74/MercadoLiebre-FacundoVillafane#1]
1-[estructura del header/main/footer] - cumple, por que en la estructura del sitio contiene lo que pide en el header, el main y el footer.
2-[foco en el footer]- cumple, primero el contenido esta centrado de manera correcta, y segundo los iconos tienen un tamaño de 2em y tienen un margen inferior de 10 pixeles.
3-[resolucion de pantalla]- cumple, por que se adapta a distintas resoluciones de pantallas.
4-[formulario de regitro de usuario]-cumple,por que cuenta con el formulario de registro de usuarios.
5-[formulario de login]-cumple,por que cuenta con el formulario de login.
6-[mensaje de error en los formularios]-cumple,por que muestre el mensaje de error cuando el usuario coloca informacion equivocada.
7-[search bar es un formulario]-no cumple, el search bar no es un formulario.
8-[animaciones y propiedades de transicion en CSS]-cumple,por que en la pagina cuenta con animaciones y propiedades de transicion.
9-[comentarios positivos]- el sitio se me hace muy facil de manejar en distintas resoluciones y no me presenta problemas.
10-[mencion a mejorar]-podria añadir una funcion que al tocar el logo me lleve al home

**Comment by FacundoVillafane74** [comment]
Listo la implementación de que al tocar el logo te redireccione al home!.
